version: '3.3'

services:
  nginx:
    image: nginx:1.17
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - web
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot:v0.36.0
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  web:
    image: getcampo/campo:0.1.1
    command: bin/rails server -b 0.0.0.0
    volumes:
      - ./data/web/uploads:/app/public/uploads
    env_file: .env
    depends_on:
      - postgres
      - redis
  worker:
    image: getcampo/campo:0.1.1
    command: bundle exec sidekiq
    env_file: .env
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:10
    volumes:
       - ./data/postgres:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
  redis:
    image: redis:3.2
    volumes:
      - ./data/redis:/data
