version: '3.3'

services:
  web:
    image: getcampo/campo:latest
    command: bin/rails server -b 0.0.0.0
    volumes:
      - ./data/storage:/app/storage
    ports:
      - 3000:3000
    env_file: .env
    depends_on:
      - postgres
      - redis
  worker:
    image: getcampo/campo:latest
    command: sidekiq
    env_file: .env
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:10
    volumes:
       - ./data/postgres:/var/lib/postgresql/data
  redis:
    image: redis:3.2
    volumes:
      - ./data/redis:/data

networks:
  default:
    attachable: true
